# Generated by Django 4.2.23 on 2025-11-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_purchasebilldetails_id_alter_purchaseitem_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billno', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('gstin', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
